fix: Result messages
AY2324S2-CS2103T-F13-1/tp pull request #122
Opened 2024-03-31 06:29 UTC by tituschewxj

## Changelog

### Visible changes
* Change person to student. Resolves #118
* Change address book to contact book.
* Use this format for NUSNet ID: `NUSNet ID`.
* Update `setcrs` message usage.

### Developer changes
* Move command-specific messages to their respective classes
* Update tests
* Command Util Classes
  * Change parameter hint to parameter constraint
  * Add new label constraint
  * Add `NEUTRAL_MESSAGES`

## UI Changes
>[!NOTE]
>`setcrs`
>
>![Screenshot 2024-03-31 141639](https://github.com/AY2324S2-CS2103T-F13-1/tp/assets/39845485/860c8805-4022-4e80-a587-5d7aea0ea8ee)

>[!NOTE]
>`edit`
>
>![Screenshot 2024-03-31 141631](https://github.com/AY2324S2-CS2103T-F13-1/tp/assets/39845485/68f49826-1e18-4c63-978b-0aa00a22b52f)

2024-04-01 08:52 UTC, saiutkarsh33 requested changes
Thanks for this PR! my only nit would be to have more fully fleshed out / elaborated javadoc comments.

2024-04-01 08:52 UTC, saiutkarsh33 commented on src/main/java/seedu/address/logic/Messages.java
Maybe having proper javadoc comments help?

2024-04-01 08:52 UTC, saiutkarsh33 commented on src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
More fully fleshed javadocs comments

2024-04-01 15:40 UTC, tituschewxj commented on src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
@saiutkarsh33 I've resolved the issue! Help me review the changes.

2024-04-03 15:27 UTC, saiutkarsh33 approved these changes
LGTM

2024-04-03 15:31 UTC, merged