127 edit person by nusnet id instead
AY2324S2-CS2103T-F13-1/tp pull request #130
Opened 2024-04-01 16:38 UTC by belligerentbeagle

Added a note in User guide about how edit command is different
Added a section in Developer guide for Design decisions
Fixed minor message inconsistencies as mentioned in #105

2024-04-01 16:44 UTC, belligerentbeagle commented
I don't understand why there are so many trailing white spaces error. 
1. Did not alter some of the lines mentioned
2. Builds fine on my machine

Hypothesis: could it be my IntelliJ setting where it probably adds a new line wherever a line exceeds a certain length?

If so, I'll undo this and re-copy paste my added text, if even possible

![Screenshot 2024-04-02 at 12 42 08 AM](https://github.com/AY2324S2-CS2103T-F13-1/tp/assets/22781279/565c1ca6-fdc9-4d5a-92c7-ef29242386e7)

2024-04-01 16:45 UTC, belligerentbeagle commented
Undoing all changes I made to DG did not seem to fix the error, still reports trailing white space...

2024-04-01 18:08 UTC, tituschewxj commented
@belligerentbeagle Go to `docs/DeveloperGuide` and add a newline at the end of the file. Our current pre-push checks do not check certain files, including markdown and fxml apparently.

2024-04-02 08:28 UTC, ForAeons approved these changes
LGTM, just remove the duplicate docs

2024-04-02 08:28 UTC, ForAeons commented on docs/DeveloperGuide.md
> +       the user's freedom, or would necessitate that the user deletes the student and re-enter all the details again.
It seems that this block is duplicated

2024-04-03 03:49 UTC, tituschewxj requested changes
Are we still handling the case when the index provided is 0 or a negative number? Because the `Invalid command format!` is still given in this case?
* I think the message should be `The student's index provided is invalid`.

2024-04-04 09:42 UTC, saiutkarsh33 approved these changes
LGTM

2024-04-04 10:44 UTC, belligerentbeagle commented on docs/DeveloperGuide.md
> +       the user's freedom, or would necessitate that the user deletes the student and re-enter all the details again.
Thanks for pointing it out, resolved.

2024-04-04 10:50 UTC, belligerentbeagle commented
> Are we still handling the case when the index provided is 0 or a negative number? Because the `Invalid command format!` is still given in this case?
> 
> * I think the message should be `The student's index provided is invalid`.

Good point raised Titus, but I personally think there isn't a need to since TAPro's response afterwards includes "INDEX (must be a positive integer)"

<img width="372" alt="Screenshot 2024-04-04 at 6 44 52 PM" src="https://github.com/AY2324S2-CS2103T-F13-1/tp/assets/22781279/c37f3b8f-8b4a-400f-9d19-2ba877df32d1">

2024-04-04 12:01 UTC, tituschewxj requested changes
Thanks for updating this PR. I have a few nits, try to address this ASAP.

2024-04-04 14:02 UTC, belligerentbeagle commented on docs/DeveloperGuide.md
> +   therefore ensures that the TA intends to perform this dangerous action.
A silver lining is that mark and unmark should be made easy, instead of requiring special, additional attention like delete does. To that end, I feel that there isn't a need for it. Since mark and umark aren't 'dangerous' operations.

2024-04-04 14:03 UTC, belligerentbeagle commented on src/main/java/seedu/address/logic/commands/EditPersonCommand.java
> +                    + "by the index number used in the displayed student list. "
Agreed

2024-04-04 14:09 UTC, tituschewxj approved these changes
LGTM!

2024-04-04 14:14 UTC, merged