Update site wide settings, AboutUs and README
AY2324S2-CS2103T-F13-1/tp pull request #17
Opened 2024-02-28 07:32 UTC by belligerentbeagle

These updates relate to issues:
#11 [Update project website: README page](https://github.com/AY2324S2-CS2103T-F13-1/tp/issues/11)

#12 [Update project website: Site wide settings](https://github.com/AY2324S2-CS2103T-F13-1/tp/issues/12)

2024-02-28 08:42 UTC, ForAeons requested changes
Just a few nit picks. Thanks a lot for looking into v1.1 issues

2024-02-28 08:42 UTC, ForAeons commented on README.md
> +* This is **an Address Book application** that is made for Computer Science Tutors for managing their students contact and performance details.<br>
Are we keeping track of the address of the students too (as a tutor)?

2024-02-28 08:42 UTC, ForAeons commented on README.md
> +[![CI Status](https://github.com/se-edu/addressbook-level3/workflows/Java%20CI/badge.svg)](https://github.com/AY2324S2-CS2103T-F13-1/tp/actions)
```suggestion
[![CI Status](https://github.com/AY2324S2-CS2103T-F13-1/tp/workflows/Java%20CI/badge.svg)](https://github.com/AY2324S2-CS2103T-F13-1/tp/actions)
```

2024-02-28 08:42 UTC, ForAeons commented on docs/site.json
>    "titleSuffix": "AddressBook Level-3",
Should we discuss on the title prefix and suffix? I am not sure about this

2024-02-29 09:47 UTC, tituschewxj commented on docs/_markbind/layouts/default.md
> +    <a slot="brand" href="{{baseUrl}}/index.html" title="Home" class="navbar-brand">MyProduct</a>
```suggestion
    <a slot="brand" href="{{baseUrl}}/index.html" title="Home" class="navbar-brand">TA Pro</a>
```

2024-02-29 09:49 UTC, belligerentbeagle commented on README.md
> +* This is **an Address Book application** that is made for Computer Science Tutors for managing their students contact and performance details.<br>
Should we change to contact book then? It sounds a little weird to me @ForAeons

2024-02-29 09:58 UTC, belligerentbeagle commented on docs/site.json
>    "titleSuffix": "AddressBook Level-3",
Was previous just following as per the Wk7 instructions, but with more consideration and since we can deviate(?) let's do TAPro - <page title> without a suffix. Reason being most times suffix is used for "online" or "live".

2024-02-29 09:59 UTC, tituschewxj commented on docs/site.json
>    "titleSuffix": "AddressBook Level-3",
The [MarkBind User Guide](https://markbind.org/userGuide/siteJsonFile.html#titleprefix) states that the prefix/suffix will appear on all page titles, so I think we should leave either `titlePrefix` or `titleSuffix` blank. In my opinion, I think we should do this:
```suggestion
  "titlePrefix": "",
  "titleSuffix": "TA Pro",
```

2024-02-29 10:00 UTC, belligerentbeagle commented on docs/_markbind/layouts/default.md
> +    <a slot="brand" href="{{baseUrl}}/index.html" title="Home" class="navbar-brand">MyProduct</a>
Thanks!

2024-02-29 10:03 UTC, tituschewxj approved these changes
LGTM!

2024-02-29 10:31 UTC, ForAeons approved these changes
LGTM!

2024-02-29 10:31 UTC, merged