Branch mark attendance feature
AY2324S2-CS2103T-F13-1/tp pull request #21
Opened 2024-02-29 07:51 UTC by Anant1902

Implements a mark command that allows a TA to mark attendance for any student for any week.

2024-02-29 08:33 UTC, tituschewxj requested changes
Great job implementing the mark command! I've went through your code and left a few comments for you to consider.

2024-02-29 08:33 UTC, tituschewxj commented on src/main/java/seedu/address/logic/Messages.java
> +            "There is no student of this nusNet!";
I think the message name can be more general, so that we can reuse it for invalid nus net ids in other commands?
```suggestion
    public static final String MESSAGE_INVALID_NUSNET =
            "There is no student of with this NUSNet ID!";
```

2024-02-29 08:33 UTC, tituschewxj commented on src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
> +            + PREFIX_WEEK + "WEEK";
Similar to the other commands, can we add an example here?

2024-02-29 08:33 UTC, tituschewxj commented on src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
> +        }
I feel that it would be better to use a guard clause here?
```suggestion
        if (!optionalPersonToMark.isPresent()) {
            throw new CommandException(Messages.MESSAGE_INVALID_NUSNET);
        }
        Person personToMark = optionalPersonToMark.get();
```

2024-02-29 08:33 UTC, tituschewxj commented on src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
> +                .add("week", weekNumber)
I think that these should follow the format used in other commands, where the `fieldName` matches with the variable name used for the `fieldValue`?
```suggestion
                .add("nusNet", nusNet)
                .add("weekNumber", weekNumber)
```

2024-02-29 08:33 UTC, tituschewxj commented on src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
> +        Person person = new Person(name, phone, email, nusNet, address, new HashSet<>(), tagList);
Perhaps we can move `new HashSet<>()` into the person constructor, since every time we add a person via the command, the new person have no attendance marked? We can add another person constructor with a different signature, and use it here:
```suggestion
        Person person = new Person(name, phone, email, nusNet, address, tagList);
```

2024-02-29 08:33 UTC, tituschewxj commented on src/main/java/seedu/address/logic/parser/MarkAttendanceCommandParser.java
> + * Parses input arguments and creates a new MarkAttendanceCommand object
Just a small nit that JavaDocs comments should end with a full stop. (And also to be consistent with the current JavaDocs style being used in the rest of the classes)

2024-02-29 08:33 UTC, tituschewxj commented on src/main/java/seedu/address/logic/parser/MarkAttendanceCommandParser.java
> +     * @throws ParseException if the user input does not conform to the expected format
There should be an empty line between the description and parameter section in JavaDocs. I've noticed this issue in some other classes as well.

2024-02-29 08:33 UTC, tituschewxj commented on src/main/java/seedu/address/logic/parser/MarkAttendanceCommandParser.java
> +    }
Perhaps we can move `arePrefixesPresent` to `ArgumentMultimap.java` (and make it public), since it is duplicated code from `AddPersonCommandParser`, and the logic doesn't seem to belong here or in `AddPersonCommandParser.java`?

2024-02-29 08:33 UTC, tituschewxj commented on src/main/java/seedu/address/model/ModelManager.java
> +    //    }
We can leave this commented code in for now, but we should remove it when we are done.

2024-02-29 08:33 UTC, tituschewxj commented on src/main/java/seedu/address/model/util/SampleDataUtil.java
Perhaps we can have some sample people with some attendance already there, instead of just using `new HashSet<>()`?

2024-03-04 17:51 UTC, Anant1902 commented on src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
> +        }
Agreed.

2024-03-04 18:01 UTC, Anant1902 commented on src/main/java/seedu/address/logic/parser/MarkAttendanceCommandParser.java
> +     * @throws ParseException if the user input does not conform to the expected format
The rest of the Command Parser classes seem to not have a space at this position for their respective parse methods though. But I don't mind adding the space. If we add, we should add to all the classes!

2024-03-05 02:44 UTC, tituschewxj commented on src/main/java/seedu/address/logic/parser/MarkAttendanceCommandParser.java
> +     * @throws ParseException if the user input does not conform to the expected format
Sure! We can add to all the classes.

2024-03-12 09:45 UTC, Anant1902 commented on src/main/java/seedu/address/logic/Messages.java
> +            "There is no student of this nusNet!";
Implemented in e6bf6760c4ee6ccd0246bec9b03915d147c6c2b2

2024-03-12 09:45 UTC, Anant1902 commented on src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
> +        }
Implemented in e6bf6760c4ee6ccd0246bec9b03915d147c6c2b2

2024-03-12 09:45 UTC, Anant1902 commented on src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
> +                .add("week", weekNumber)
Implemented in e6bf6760c4ee6ccd0246bec9b03915d147c6c2b2

2024-03-12 09:45 UTC, Anant1902 commented on src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
> +        Person person = new Person(name, phone, email, nusNet, address, new HashSet<>(), tagList);
Implemented in e6bf6760c4ee6ccd0246bec9b03915d147c6c2b2

2024-03-12 09:46 UTC, Anant1902 commented on src/main/java/seedu/address/model/util/SampleDataUtil.java
Implemented in e6bf6760c4ee6ccd0246bec9b03915d147c6c2b2

2024-03-12 13:57 UTC, belligerentbeagle commented on src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
> +        }
I agree with this!

2024-03-12 15:13 UTC, tituschewxj reviewed
Thanks for making the changes! You can consider using the message usage helper functions I've added.

2024-03-13 02:22 UTC, Anant1902 commented on src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
> +            + "Example: " + COMMAND_WORD + " " + PREFIX_NUSNET + "e0123456 " + PREFIX_WEEK + " 1";
Will implement this once I merge the upstream master into this PR!

2024-03-13 05:39 UTC, ForAeons approved these changes
LGTM, just fix the comments from the other reviewers if theres any

2024-03-13 11:08 UTC, belligerentbeagle approved these changes
LGTM, despite minor nits like returning an CommandResult instance instead of CommandException, I am approving first so we can start on Unmark command. Perhaps the aforementioned nits can be fixed in future feature PRs.

2024-03-14 04:37 UTC, tituschewxj approved these changes
LGTM! Although there are a few style issues, and some pending issues, I'm approving this first, so as to let other PRs move forward. Issues have been created, and assigned to @Anant1902, which we can resolve in the next iteration.

2024-03-14 04:37 UTC, tituschewxj commented on src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
> +    /**
The first sentence of the Javadoc should be a summary of the method. See the section on summary fragment in the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment).

2024-03-14 04:43 UTC, merged