docs: Changes the address prefix and example to major
AY2324S2-CS2103T-F13-1/tp pull request #232
Opened 2024-04-06 14:44 UTC by Anant1902

Resolves #160, #168, #171, #184, which all refer to outdated addstu command usage and example.
Partially resolves #165

2024-04-06 16:38 UTC, tituschewxj requested changes
Thanks for this. I have left some nits regarding the screenshots. We can refer to #231 for tips on formatting the docs.

2024-04-06 16:38 UTC, tituschewxj commented on docs/UserGuide.md
> +<img width="1470" alt="Screenshot 2024-04-06 at 10 30 53 PM" src="https://github.com/AY2324S2-CS2103T-F13-1/tp/assets/60879977/7752d686-20ff-4112-bb3c-a3441c22577d">
Consider putting the file inside the `docs/images` folder instead. And also name the file more appropriately. We should also delete the `images/main_window_ui.png` as it is outdated.

The image with is too large, and the image is cut off. The window size is not the same size as a new user's window.

To fix this, delete the `preferences.json` file and `data` directory and take another screenshot.

Additionally, we can include `class="rounded-image"` to round the corners of the image. It makes the screenshot look more polished.

2024-04-06 16:38 UTC, tituschewxj commented on docs/UserGuide.md
> +<img width="857" alt="Screenshot 2024-04-06 at 10 32 22 PM" src="https://github.com/AY2324S2-CS2103T-F13-1/tp/assets/60879977/7da9f175-14df-422f-8f3c-34c3be7fca00">
This image is fine, but we should rename it, and move it into the project directories and delete the previous `help_window_ui.png`, and add rounded corners to this image.

Additionally, the image is cut off in the pdf version. I think the max width of an image to show correctly in the pdf would be 800, if the image is in a box. So we should reduce the width of this image to 800.

2024-04-06 16:38 UTC, tituschewxj commented on docs/UserGuide.md
>  [//]: # (TODO: update this image once the help window is finalized in v1.4)
Delete the todo since the image is updated.

2024-04-06 16:38 UTC, tituschewxj commented on docs/UserGuide.md
> +<img width="618" alt="Screenshot 2024-04-06 at 10 33 37 PM" src="https://github.com/AY2324S2-CS2103T-F13-1/tp/assets/60879977/ebf1d631-b86a-41a6-b027-b27ce8fa049c">
Ditto. We can round the corners here too.

2024-04-07 06:44 UTC, tituschewxj commented
Resolves #217 also

2024-04-07 09:37 UTC, Anant1902 commented
Also resolves #218

2024-04-07 10:07 UTC, Anant1902 commented
Resolves #213 too

2024-04-07 10:09 UTC, ForAeons commented
Can just help to make sure all the parts edited by https://github.com/AY2324S2-CS2103T-F13-1/tp/pull/236/files is covered here too

2024-04-07 10:13 UTC, Anant1902 commented
> Can just help to make sure all the parts edited by https://github.com/AY2324S2-CS2103T-F13-1/tp/pull/236/files is covered here too

Hi yes, just updated for edit too! Aplogies for missing it out. Should cover everything now

2024-04-07 10:22 UTC, ForAeons commented
> > Can just help to make sure all the parts edited by https://github.com/AY2324S2-CS2103T-F13-1/tp/pull/236/files is covered here too
> 
> Hi yes, just updated for edit too! Aplogies for missing it out. Should cover everything now

Line 199

2024-04-07 10:23 UTC, Anant1902 commented
> > > Can just help to make sure all the parts edited by https://github.com/AY2324S2-CS2103T-F13-1/tp/pull/236/files is covered here too
> > 
> > 
> > Hi yes, just updated for edit too! Aplogies for missing it out. Should cover everything now
> 
> Line 199

bro my command f is not working

2024-04-07 10:26 UTC, Anant1902 commented
Ok done @ForAeons can help check if g now?

2024-04-07 10:51 UTC, tituschewxj approved these changes
LGTM!

2024-04-07 11:01 UTC, Anant1902 commented
> LGTM!
> 
> Note
> 
> Putting `resolves` in a comment does not automatically resolve the issue when this is merged. Have to manually link it or put it in the main comment.
> 
> Additionally, each issue must have `resolves` before it: For example: `Resolves #160, resolves #168, resolves #171, resolves #184` will resolve all 4 issues but `Resolves #160, #168, #171, #184` will only resolve `#160` automatically.

Got it! Thanks a lot Titus.

2024-04-07 13:53 UTC, tituschewxj reviewed
There's a few more things I spotted still while reviewing things again.

2024-04-07 13:53 UTC, tituschewxj commented on docs/UserGuide.md
>  * `addstu n/Betsy Crowe nn/e01234567 t/friend e/betsycrowe@example.com a/Newgate Prison p/1234567 t/criminal`
I noticed that this is wrong:
```suggestion
* `addstu n/Betsy Crowe nn/e01234567 t/friend e/betsycrowe@example.com m/Mathematics p/1234567 t/club`
```

2024-04-07 13:53 UTC, tituschewxj commented on docs/UserGuide.md
> +Format: `addstu n/NAME p/PHONE_NUMBER e/EMAIL nn/NUSNET_ID m/MAJOR [t/TAG]…​`
From an unrelated issue, that it should follow the format inside our help window:
* I have added the issue here: #252 
```suggestion
Format: `addstu n/NAME nn/NUSNET [p/PHONE] [e/EMAIL] [m/MAJOR] [t/TAG]…​`
```

2024-04-07 23:54 UTC, ForAeons requested changes
Just one nit pick, the rest LGTM

2024-04-07 23:54 UTC, ForAeons commented on docs/UserGuide.md
> +| **Add Student**    | `addstu n/NAME p/PHONE_NUMBER e/EMAIL nn/NUSNET_ID m/MAJOR [t/TAG]…​` <br> e.g., `add n/James Ho p/22224444 e/jamesho@example.com nn/e1234567 m/Computer Science t/friend t/coll
Phone and major fields are optional right

2024-04-07 23:55 UTC, ForAeons approved these changes
LGTM

2024-04-07 23:55 UTC, merged