docs: update user guide and make find command docs consistent
AY2324S2-CS2103T-F13-1/tp pull request #234
Opened 2024-04-07 03:11 UTC by ForAeons

Resolves https://github.com/AY2324S2-CS2103T-F13-1/tp/issues/204

2024-04-07 04:32 UTC, tituschewxj requested changes
We should be consistent with the help window: `find KEYWORD [MORE_KEYWORDS]…​`, as we cannot enhance the text in the help window. 

![image](https://github.com/AY2324S2-CS2103T-F13-1/tp/assets/39845485/ce1d5601-6326-45e4-94d8-25bda70be850)

In addition, we could add another info box in the UG on why we have two `KEYWORD` and `MORE_KEYWORDS` and give an explanation for each parameter.
* This is to provide greater **clarity**, as listing the parameter name twice in a single command format may cause confusion.
* `KEYWORD`: This is a required keyword
* `[MORE_KEYWORDS]...`: This is an optional field, that can accept more keywords.

2024-04-07 06:51 UTC, ForAeons commented
> We should be consistent with the help window: `find KEYWORD [MORE_KEYWORDS]…​`, as we cannot enhance the text in the help window.
> 
> ![image](https://private-user-images.githubusercontent.com/39845485/320252674-ce1d5601-6326-45e4-94d8-25bda70be850.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzI5NTAsIm5iZiI6MTcxMjQ3MjY1MCwicGF0aCI6Ii8zOTg0NTQ4NS8zMjAyNTI2NzQtY2UxZDU2MDEtNjMyNi00NWU0LTk0ZDgtMjViZGE3MGJlODUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA2NTA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZjRmMjFkMmY0MTY3YzE5MjY0MGE2NGRjNDNjODE2NTRlNDIyNzYwZDA2N2ZlZGQxZDUyMTNkNzc2N2E2ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6We0wQ2Au2CpYTIwzUhLHjsucV5c9LjmX3DEUyHIHXQ)
> 
> In addition, we could add another info box in the UG on why we have two `KEYWORD` and `MORE_KEYWORDS` and give an explanation for each parameter.
> 
>     * This is to provide greater **clarity**, as listing the parameter name twice in a single command format may cause confusion.
> 
>     * `KEYWORD`: This is a required keyword
> 
>     * `[MORE_KEYWORDS]...`: This is an optional field, that can accept more keywords.

Good point, updated

2024-04-07 09:55 UTC, Anant1902 approved these changes
LGTM

2024-04-07 10:48 UTC, tituschewxj requested changes
Just a few more nits.

In addition, can we add the following in the `**About the command format:**` box in the UG, maybe after the extraneous parameters part:
```
<box type="tip" seamless>

<span class="semi-bold">Each parameter will appear at most once in the command format.</span>

This provides greater clarity on how a command should be used.
</box>
```

2024-04-07 10:48 UTC, tituschewxj commented on docs/UserGuide.md
> +- `[MORE_KEYWORDS]` are additional, optional keywords to search for. You can have any number of additional keywords.
```suggestion
- `[MORE_KEYWORDS]...` are additional, optional keywords to search for. You can have any number of additional keywords.
```

2024-04-07 10:48 UTC, tituschewxj commented on docs/UserGuide.md
> +**Parameters of find command:**
```suggestion
**Parameters of `find` command:**
```

2024-04-08 01:53 UTC, tituschewxj approved these changes
LGTM! Resolve the merge conflicts and we can merge this.

2024-04-08 06:12 UTC, merged