Update ug name
AY2324S2-CS2103T-F13-1/tp pull request #258
Opened 2024-04-08 09:05 UTC by saiutkarsh33

Solves #148

2024-04-08 09:34 UTC, tituschewxj commented
Could you not continue this branch https://github.com/saiutkarsh33/tp/tree/update-ug-name from a another branch https://github.com/saiutkarsh33/tp/tree/name-test

Doing so, you will not need to rebase your changes once #256 is merged.

You can move your changes for solving #148, into #256, since is both regarding the `setcrs` command.

2024-04-08 09:42 UTC, tituschewxj commented
>[!IMPORTANT]
>Alternatively, I will close the other PRs and will review this, since this is the latest.

Also see my review from here: https://github.com/AY2324S2-CS2103T-F13-1/tp/pull/256#pullrequestreview-1985802001

2024-04-08 09:55 UTC, tituschewxj requested changes
I have a few nits. I moved my nits from #256 to here, so it is easier for you to change it.

>[!TIP]
>You should also refer to #231 when updating the UG and DG.

2024-04-08 09:55 UTC, tituschewxj commented on docs/UserGuide.md
> +Format: `setcrs COURSE_code`
Parameters should be upper case.
```suggestion
Format: `setcrs COURSE_CODE`
```

2024-04-08 09:55 UTC, tituschewxj commented on src/main/java/seedu/address/logic/commands/SetCourseCommand.java
> +    public static final String MESSAGE_SUCCESS = "Successfully updated course code";
>[!IMPORTANT]
>This should not violate the feature freeze, since it does not add more information. The current text is incorrect as pointed out in #172, Course name refers to the full name of the course, but course code refers to the code, so is strictly incorrect in this sense. 

>Q6: Can we tweak error/help messages (or other text shown to the user)?
>
>A: Only if the current text is incorrect (i.e., a bug). Adding more information or otherwise 'enhancing' the text is not allowed. Other points to note,
>
>Spelling errors and grammar errors in the UI (or docs) can be fixed, as they are errors by definition.
>If a user action fails silently, it can be fixed to inform the user of the problem.
>Making user-facing info more specific/informative (e.g., changing a generic error message Command format is invalid into a more specific error message The parameter p/ in the command is not valid) is an enhancement i.e., not allowed.

So it should be fine to change this.

2024-04-08 09:55 UTC, tituschewxj commented on docs/UserGuide.md
>  Courses are case-insensitive.
```suggestion
Course codes are case-insensitive.
```

2024-04-08 09:55 UTC, tituschewxj commented on src/test/java/seedu/address/model/person/NameTest.java
> +        assertFalse(Name.isValidName("Peter  T")); // Double space
Thanks for adding this.

2024-04-08 09:55 UTC, tituschewxj commented on docs/UserGuide.md
> +* Name cannot be empty or spaces only, contain only alphabets and cannot have double spaces
```suggestion
* Name cannot be empty or spaces only, contain only alphabets and cannot have double spaces.
```

2024-04-10 02:09 UTC, tituschewxj approved these changes
LGTM! I approved this first, since I have left my other comments on #263.

2024-04-10 05:38 UTC, ForAeons approved these changes
LGTM, please resolve the merge conflicts and we can merge it

2024-04-11 10:06 UTC, merged