Update ug setcrs
AY2324S2-CS2103T-F13-1/tp pull request #263
Opened 2024-04-08 15:04 UTC by saiutkarsh33

Solves #139

2024-04-10 01:53 UTC, tituschewxj commented
@saiutkarsh33 Could you rebase your PR, as there are merge conflicts?

2024-04-10 02:08 UTC, tituschewxj requested changes
I have a few nits. 

The changes you made in your previous PRs are duplicated here. Hence we should only focus on the issues in this PR. There will likely be a need to rebase.

>[!IMPORTANT]
>This PR can only be merged after #258 is merged!

2024-04-10 02:08 UTC, tituschewxj commented on docs/UserGuide.md
>  Courses are case-insensitive.
We can consider using boxes to add whitespace, which improves readability.
```suggestion
<box type="info" light>

Course codes are case-insensitive.
</box>

```

2024-04-10 02:08 UTC, tituschewxj commented on docs/UserGuide.md
> +<img src="images/ug/setcrs_error.png" alt="Setcrs Error" class="rounded-image" width="800px"/>
We can put this into a separate box, and add a line to describe the image.
```suggestion
<box type="warning" light>

Course code should follow the format "XX1234Y", Y is optional.

When an invalid course code is entered, the follow error message appears:

<img src="images/ug/setcrs_error.png" alt="Setcrs Error" class="rounded-image" width="800px"/>
</box>
```

2024-04-10 02:08 UTC, tituschewxj commented on docs/UserGuide.md
> +* Name cannot be empty or spaces only, contain only alphabets and cannot have double spaces
We can put this in a box to improve readability:
```suggestion

<box type="warning" light>

Name cannot be empty or spaces only, contain only alphabets and cannot have double spaces 
</box>
```

2024-04-11 14:52 UTC, belligerentbeagle requested changes
Overall LGTM, just one typo! Can also consider Titus' above recommendation on the light (i think now seamless) box

2024-04-12 12:38 UTC, tituschewxj approved these changes
LGTM! Except that this doesn't really resolve: https://github.com/AY2324S2-CS2103T-F13-1/tp/issues/167, to resolve this we should also have a successful example where the course name is set. We can do this in another PR.

2024-04-14 09:17 UTC, belligerentbeagle commented
Hi @saiutkarsh33 , do also consider adding a note that this app would not support courses with more than 2 prefixes since it is meant for CS module TAs. 
See
"Make it clear that the courses being taught are CS courses. See [PE-D][Tester B] Unable to set course code for certain formats of course codes.  #164" in #252

2024-04-14 16:07 UTC, Anant1902 commented
> Hi @saiutkarsh33 , do also consider adding a note that this app would not support courses with more than 2 prefixes since it is meant for CS module TAs. This would help you defend against an issue like #164 See "Make it clear that the courses being taught are CS courses. See [PE-D][Tester B] Unable to set course code for certain formats of course codes. #164" in #252

@saiutkarsh33 Bumping this hahahah

2024-04-15 07:10 UTC, tituschewxj commented
I'll force merge this and fix the issues of duplicated `Course is shown...`, as I don't want this to have more merge conflicts.

2024-04-15 07:10 UTC, merged