docs: update dg use cases
AY2324S2-CS2103T-F13-1/tp pull request #289
Opened 2024-04-12 09:45 UTC by ForAeons

2024-04-12 12:35 UTC, tituschewxj requested changes
Thanks for doing this! I have a few nits.

I feel that the use cases are a bit incomplete, as the final step that TAPro successfully does the command is missing.

Also, it may be clearer, if we start line in the use case with the User or TAPro. (only if applicable, as sometimes it may be clearer not to)

2024-04-12 12:35 UTC, tituschewxj commented on docs/DeveloperGuide.md
> +**: Use case: Retrieve a more recent successful command input**
```suggestion
**Use case: Retrieve a more recent successful command input**
```

2024-04-12 12:35 UTC, tituschewxj commented on docs/DeveloperGuide.md
> +**: Use case: Retrieve a previous successful command input**
```suggestion
**Use case: Retrieve a previous successful command input**
```

2024-04-12 12:35 UTC, tituschewxj commented on docs/DeveloperGuide.md
> +    * 3a1. No action is taken.
Technically, the text in the command box is blank if no more recent command input is available.

2024-04-12 12:35 UTC, tituschewxj commented on docs/DeveloperGuide.md
Can we add week number here: `by providing the student's NUSNet ID and week number to mark/unmark the attendance for`.

And then TAPro marks/unmarks the attendance for that student for that week.

We should also add extensions if the student doesn't exist, or if the week doesn't exist, or if the attendance is already marked/unmarked.

2024-04-12 12:35 UTC, tituschewxj commented on docs/DeveloperGuide.md
> +    Use case ends.
This use case is a bit incomplete, we should state that TAPro shows the students that are found.

We can also add an extension that no result is found, so TAPro shows no students.

2024-04-12 12:35 UTC, tituschewxj commented on docs/DeveloperGuide.md
> +   Use case ends.
We can add that TAPro successfully clears all data.

2024-04-12 12:35 UTC, tituschewxj commented on docs/DeveloperGuide.md
> +
Perhaps, this use case is a bit incomplete, we can add that TAPro successful edits the student details.

2024-04-12 12:35 UTC, tituschewxj commented on docs/DeveloperGuide.md
Perhaps we may want to add that TAPro successfully does something.

2024-04-12 12:35 UTC, tituschewxj commented on docs/DeveloperGuide.md
> +3. The previous successful command input is shown in the command box.
```suggestion
3. TAPro displays the successful command input in the command box.
```

2024-04-12 12:35 UTC, tituschewxj commented on docs/DeveloperGuide.md
> +3. The more recent successful command input is shown in the command box.
```suggestion
3. TAPro displays a more recent successful command input in the command box.
```

2024-04-12 13:22 UTC, ForAeons commented on docs/DeveloperGuide.md
Very good point

2024-04-12 14:45 UTC, ForAeons commented on docs/DeveloperGuide.md
I am not sure what you mean titus, do you mind elaborating?

2024-04-12 15:36 UTC, tituschewxj approved these changes
LGTM! Just resolve the remaining nits, and we can merge this.

2024-04-13 00:48 UTC, ForAeons commented on docs/DeveloperGuide.md
I see. I also moved the section on top of addstu use case.

2024-04-13 01:53 UTC, merged