Ug labelled screenshots
AY2324S2-CS2103T-F13-1/tp pull request #293
Opened 2024-04-13 09:06 UTC by saiutkarsh33

2024-04-13 13:54 UTC, tituschewxj requested changes
Thanks for updating the images. I have some nits. Also please pull the latest version of our codebase, as the UG is out of date here.

2024-04-13 13:54 UTC, tituschewxj commented on docs/UserGuide.md
Please pull the latest version of the UserGuide, as there are many new changes missing here.

2024-04-13 13:54 UTC, tituschewxj commented on docs/images/ug-screenshots/addstu_after.png
Use `Student with NUSNet ID E1234567 added` instead, as this is the convention we are using.

2024-04-13 13:54 UTC, tituschewxj commented on docs/images/ug-screenshots/delstu_after.png
Use `Student with NUSNet ID E1234567 deleted` instead, as this is the convention we are using.

2024-04-13 13:54 UTC, tituschewxj commented on docs/images/ug-screenshots/find_after.png
Use `Students with 'alex' and 'Devin' in their names displayed` instead, as `Devin` is entered with a uppercase `D`.

2024-04-13 13:54 UTC, tituschewxj commented on docs/images/ug-screenshots/mark_after.png
Use `Student with NUSNet ID E1234567's attendance for week 12 marked` instead, as this is the convention we are using.

2024-04-13 13:54 UTC, tituschewxj commented on docs/images/ug-screenshots/mark_before.png
Use `Student with NUSNet ID E1234567's attendance for week 12 not marked` instead, as this is the convention we are using.

2024-04-13 13:54 UTC, tituschewxj commented on docs/images/ug-screenshots/unmark_after.png
Use `Student with NUSNet ID E1234567's attendance for week 12 unmarked` instead, as this is the convention we are using.

2024-04-13 13:54 UTC, tituschewxj commented on docs/images/ug-screenshots/unmark_before.png
Use `Student with NUSNet ID E1234567's attendance for week 12 not unmarked` instead, as this is the convention we are using.

2024-04-13 13:54 UTC, tituschewxj commented on docs/images/ug-screenshots/launch.png
`Command input panel` should be `Command input box` instead.

2024-04-13 13:54 UTC, tituschewxj commented on docs/images/ug-screenshots/launch.png
`Error/ Success Message panel` can be `Result message panel` instead. This is because it is easier to refer to it as `Result message panel` than `Error/ Success Message panel` when we want to refer to the UI.

2024-04-13 14:11 UTC, saiutkarsh33 commented on docs/UserGuide.md
I pulled, using git pull upstream master, 
Says already up to date

2024-04-13 17:29 UTC, tituschewxj commented on docs/UserGuide.md
Did you rebase your changes onto this branch?

```bash
git switch ug-screenshots
git rebase master
```

2024-04-14 14:05 UTC, tituschewxj approved these changes
LGTM!

2024-04-14 14:06 UTC, merged