Feat 20 unmark student attendance
AY2324S2-CS2103T-F13-1/tp pull request #52
Opened 2024-03-14 07:58 UTC by belligerentbeagle

Added unmark function and improved OOP use in mark command by using Messages.java's constants

2024-03-14 08:00 UTC, belligerentbeagle commented
Turning into draft to add docs first

2024-03-15 04:01 UTC, belligerentbeagle commented
Now improving code coverage as per https://nus-cs2103-ay2324s2.github.io/website/admin/tp-w12.html#3-polish-the-deliverables

2024-03-16 04:13 UTC, belligerentbeagle commented
Resolves #20

2024-03-16 14:26 UTC, tituschewxj requested changes
Thanks for the PR! I have some nits for consideration.

Additionally, avoid adding an blank lines into files such as in `AddressBook.java`, `Model.java` `ModelManager.java`, that doesn't do anything style wise (according to [this](https://google.github.io/styleguide/javaguide.html#s4.6.1-vertical-whitespace)). While not really an coding style issue, you may want to remove these empty lines for greater consistency and readability within our codebase. You may also want to consider structuring your vertical whitespace better, as too much vertical whitespace can make code harder to read and makes our codebase less consistent overall.

2024-03-16 14:26 UTC, tituschewxj commented on src/main/java/seedu/address/model/Model.java
> +
Try not to leave blank lines in parts of the code that are untouched.

2024-03-16 14:26 UTC, tituschewxj commented on src/test/java/seedu/address/logic/commands/MarkAttendanceCommandTest.java
>          assertCommandSuccess(command, model, expectedCommandResult, expectedModel1);
Consider structuring the code more logically, as it makes the code more readable, instead of just adding a vertical whitespace between every statement:
```java
        HashSet<WeekNumber> aliceAttendanceUpdated = new HashSet<>(ALICE.getAttendance());
        aliceAttendanceUpdated.add(testValidWeekNo6);
        Person aliceChanged = new Person(ALICE.getName(), ALICE.getPhone(), ALICE.getEmail(), ALICE.getNusNet(),
                ALICE.getAddress(), aliceAttendanceUpdated, ALICE.getTags());

        CommandResult expectedCommandResult =
                new CommandResult(MESSAGE_MARK_ATTENDANCE_SUCCESS + aliceChanged);
                new CommandResult("Marked attendance for student: Alice Pauline, e0000001, Week 6");

        MarkAttendanceCommand command = new MarkAttendanceCommand(testValidNusNet, testValidWeekNo6);
        
        Model expectedModel1 = expectedModel;
        expectedModel1.setPerson(ALICE, aliceChanged);

        assertCommandSuccess(command, model, expectedCommandResult, expectedModel1);
```

2024-03-16 14:26 UTC, tituschewxj commented on src/test/java/seedu/address/logic/commands/UnmarkAttendanceCommandTest.java
> +                new UnmarkAttendanceCommand(new NusNet("E0123457"), testValidWeekNo6);
For readability, we may also want to extract out `new NusNet("E0123457")` into an explaining variable, instead of using a magic literal.

2024-03-16 14:26 UTC, tituschewxj commented on docs/DeveloperGuide.md
> +      t/friends t/owesTutorial2`
Should we use generic numbering for ordered lists here? Generic numbers are converted to the correct numbers by the GitHub markdon renderer. It allows us to easily add more items later.

2024-03-16 18:52 UTC, belligerentbeagle commented
> Thanks for the PR! I have some nits for consideration.
> 
> Additionally, avoid adding an blank lines into files such as in `AddressBook.java`, `Model.java` `ModelManager.java`, that doesn't do anything style wise (according to [this](https://google.github.io/styleguide/javaguide.html#s4.6.1-vertical-whitespace)). While not really an coding style issue, you may want to remove these empty lines for greater consistency and readability within our codebase. You may also want to consider structuring your vertical whitespace better, as too much vertical whitespace can make code harder to read and makes our codebase less consistent overall.

Wow. Appreciate the detailed feedback Titus, I'll look through them and make the changes tomorrow

2024-03-18 14:33 UTC, belligerentbeagle commented on build.gradle
> +    testImplementation 'junit:junit:4.13.1'
Hmm I'm actually not sure how that got added because I don't remember doing this intentionally... this is very strange

Let me remove it!

2024-03-18 14:34 UTC, belligerentbeagle commented on docs/DeveloperGuide.md
> +      t/friends t/owesTutorial2`
great suggestion, wilco!

2024-03-18 16:16 UTC, tituschewxj approved these changes
LGTM! Overall, I think most issues have been resolved and is almost ready to be merged. I've left a remark in `UnmarkAttendanceCommandTest.java` for you to consider, I'll approve this PR first but do resolve it.

2024-03-18 16:16 UTC, tituschewxj commented on src/test/java/seedu/address/logic/commands/UnmarkAttendanceCommandTest.java
In `execute_validNusNetValidWeekNumber_unmarkSuccess` and `execute_validNusNetDuplicateWeekNumber_unmarkSuccess`, maybe you can consider grouping the lines more logically together instead of leaving whitespace, for better readability?

2024-03-19 04:02 UTC, Anant1902 commented on docs/DeveloperGuide.md
> +### Adding a person
Agreed. Should we leave this for v1.3?

2024-03-19 04:19 UTC, Anant1902 approved these changes
LGTM! Great job on this PR Ethan. Approving this for now but have left some comments!

2024-03-19 04:19 UTC, Anant1902 commented on src/main/java/seedu/address/logic/Messages.java
> +    public static final String MESSAGE_MARKED_ATTENDANCE_SUCCESS = "Marked attendance for student: ";
There does seem to be inconsistency with the usage of 'person' and 'student' at different parts of the codebase. As Titus brought up (https://github.com/AY2324S2-CS2103T-F13-1/tp/pull/52#discussion_r1528829740), lets standardize to 'student' everywhere

2024-03-19 04:19 UTC, Anant1902 commented on src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
> +            String formattedMessage = String.format("%1$s%2$s, %3$s, Week %4$s",
Thanks a lot for implementing this!

2024-03-19 04:19 UTC, Anant1902 commented on src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
Great work implementing this. I like that its implementation is similar to that of MarkAttendanceCommand - it improves code readability and ensures standardization.

2024-03-19 04:19 UTC, Anant1902 commented on src/main/java/seedu/address/logic/parser/UnmarkAttendanceCommandParser.java
Ditto. Good job!

2024-03-19 04:19 UTC, Anant1902 commented on src/test/java/seedu/address/logic/commands/MarkAttendanceCommandTest.java
> +                new CommandResult("Marked attendance for student: Alice Pauline, e0000001, Week 6");
Is there a reason for this change? I am okay with this implementation too but just curious!

2024-03-19 04:19 UTC, Anant1902 commented on src/test/java/seedu/address/logic/commands/MarkAttendanceCommandTest.java
> +                new CommandResult("Re-marked Attendance for student: Alice Pauline, e0000001, Week 1");
Ditto.

2024-03-19 04:47 UTC, merged