[Draft] Branch set course command
AY2324S2-CS2103T-F13-1/tp pull request #53
Opened 2024-03-14 09:05 UTC by saiutkarsh33

- Created logic for setcrs method
- Changing course will change the title of main window
- Created Course storage class, amongst others in the Storage package

2024-03-18 17:46 UTC, tituschewxj requested changes
Thanks for implementing the set course command! This is quite a long PR, so ideally try to keep your PRs shorter in future. I have left my comments.

If you have time, please do a self-review of your own code to remove redundant vertical whitespace, as the number of empty lines is a bit excessive and inconsistent. I only highlighted a few instances, but there are more places that have this issue.

Also, do add `// TODO` to remind ourselves of incomplete tests.

2024-03-18 17:46 UTC, tituschewxj commented on src/main/java/seedu/address/model/CourseName.java
> +     * Creates a Course using the course in the {@code toBeCopied}
```suggestion
     * Creates a Course using the course in the {@code toBeCopied}.
```

2024-03-18 17:46 UTC, tituschewxj commented on src/main/java/seedu/address/model/CourseName.java
> + * Duplicates are not allowed (by .isSamePerson comparison)
This JavaDoc comment seems to be copied from `AddressBook.java`. Consider rewriting this comment.

2024-03-18 17:46 UTC, tituschewxj commented on src/main/java/seedu/address/logic/parser/SetCourseCommandParser.java
> + * Parses input arguments and creates a new {@code SetCourseCommand} object
```suggestion
 * Parses input arguments and creates a new {@code SetCourseCommand} object.
```

2024-03-18 17:46 UTC, tituschewxj commented on src/main/java/seedu/address/model/course/Course.java
> +     * and can optionally end with an uppercase letter.
Perhaps we can reword this. It's not just Computer Science, but also NUS courses in general. Not a big issue.

2024-03-18 17:46 UTC, tituschewxj commented on src/main/java/seedu/address/model/course/Course.java
> + * scenarios where course codes might need to be updated or corrected.
A tip, you can use `<p>` and `<br/>` tags to structure long JavaDoc comments to be more readable. You may want to do that here.

2024-03-18 17:46 UTC, tituschewxj commented on src/main/java/seedu/address/model/course/Course.java
> +            "Course code should follow the format \"XX1234Y\", Y is optional";
We can consider using a constant for the format instead of a magic literal here:
```suggestion
    public static final String COURSE_CODE_FORMAT = "XX1234Y";
    public static final String MESSAGE_CONSTRAINTS =
            "Course code should follow the format \"" + COURSE_CODE_FORMAT + "\", Y is optional";
```

2024-03-18 17:46 UTC, tituschewxj commented on src/main/java/seedu/address/model/util/SampleDataUtil.java
> +        courseName.setCourse(new Course("XX1234Y"));
Perhaps we can use a constant I suggested in the earlier comment here, instead of a magic literal:
```suggestion
        courseName.setCourse(new Course(COURSE_CODE_FORMAT));
```

2024-03-18 17:46 UTC, tituschewxj commented on src/main/java/seedu/address/storage/JsonCourseNameStorage.java
> +        if (!jsonCourse.isPresent()) {
Ditto

2024-03-18 17:46 UTC, tituschewxj commented on src/main/java/seedu/address/storage/CourseStorageName.java
> +     * @throws IOException if there was any problem writing to the file.
```suggestion
     * Saves the given {@link ReadOnlyCourseName} to the storage.
     *
     * @param course cannot be null.
     * @throws IOException if there was any problem writing to the file.
```

2024-03-19 04:53 UTC, Anant1902 commented
@saiutkarsh33 Could you run the Github Workflow checks for this PR! Wondering why they didn't auto run.

2024-03-19 09:05 UTC, tituschewxj reviewed
Thanks for the changes! I've left a few more comments.

2024-03-20 01:51 UTC, ForAeons requested changes
Thanks a lot for this big PR, your logic for updating ui is good but I have some problems with the underlying implementation of storage and abstractions. Specifically, course_name should be a field of the addressbook.json file, and you should try to avoid passing model and storage directly to ui as per our discussion on telegram

2024-03-20 01:51 UTC, ForAeons commented on src/main/java/seedu/address/logic/commands/SetCourseCommand.java
> +            "Sets Course", "course code", "CS2104");
It is slightly annoying that I have to caplock/hold down shift to enter the course code, can we just allow xx1234y, where x and y is alphabetic and non case sensitive. Then when we parse the course code, we convert all alphabets to uppercase in the logic

2024-03-20 01:51 UTC, ForAeons commented on src/main/java/seedu/address/logic/commands/SetCourseCommand.java
> +        return course.equals(e.course);
so here, the course comparison should be case insensitive comparison

2024-03-20 01:51 UTC, ForAeons commented on src/main/java/seedu/address/logic/parser/ParserUtil.java
> +        String trimmedCode = code.trim();
And this is where you convert the course code to uppercase

2024-03-20 01:51 UTC, ForAeons commented on src/main/java/seedu/address/model/UserPrefs.java
> +    private Path courseNameFilePath = Paths.get("data", "coursename.json");
This is quite different than what we discussed I believe.

We were talking about how essentially, each `addressbook.json` holds all the student information and course information. Example cs2030s.json
```
{
  course_name: "CS2030S",
  persons: []
}
```
So essentially, its `addressbook.json` and `coursename.json` combined, rather than having 2 separate files.

And the expected behavior of `setcrs` command is simple to update the `course_name` field of this json object.

On initial load, there is no pre-existing data, and we do not know which course_name.json file to load from, we can just create an arbitrary file generic_course.json for example. Alternatively, we can walk the ./data dir and load the first json file we find, if any

2024-03-20 01:51 UTC, ForAeons commented on src/main/java/seedu/address/ui/MainWindow.java
> +    public MainWindow(Stage primaryStage, Logic logic, Model model, Storage storage) {
As per our discussion in the telegram chat, I think we all logic should be handled in the Logic object (2nd parameter). Your UI should not directly interact with Model or Storage. You can add methods to Logic interface and call the methods through the logic object

2024-03-20 01:51 UTC, ForAeons commented on src/main/java/seedu/address/ui/UiManager.java
> +    public UiManager(Logic logic, Model model, Storage storage) {
ditto

2024-03-20 08:23 UTC, saiutkarsh33 commented on src/test/java/seedu/address/logic/commands/AddCommandTest.java
Will take note of this in v1.3, added a // TODO.

2024-03-21 02:00 UTC, tituschewxj approved these changes
LGTM! Thanks for all the updates! Apart from the issues raised, it's ready to merge.

2024-03-21 02:01 UTC, merged