feat: autocomplete nusnet id
AY2324S2-CS2103T-F13-1/tp pull request #71
Opened 2024-03-21 13:29 UTC by ForAeons

2024-03-27 07:43 UTC, Anant1902 approved these changes
LGTM! Thanks for this feature @ForAeons.

Left a nit, but all in all, great work. Good job with the test files too.

2024-03-27 07:43 UTC, Anant1902 commented on src/main/java/seedu/address/logic/LogicManager.java
> +        AutoCompleteCommand.initialize(
Would it be a better idea to have the initialize() function not take in any parameters? Since you are initialising for all commands anyways, you could abstract initialisation for all within the AutoCompleteCommand itself

2024-03-27 13:07 UTC, ForAeons commented on src/main/java/seedu/address/logic/LogicManager.java
> +        AutoCompleteCommand.initialize(
Thanks a lot for the review, can I clarify something with you regarding the comment? Since the command Trie are stored as a static field of the AutoCompleteCommand, the initialization should be called once only (as opposed to creating on for every instance of AutoCompleteCommand). Where do you think is a better place to initialize the command Trie?

2024-03-27 13:11 UTC, ForAeons commented on src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
> -                DeletePersonCommand.COMMAND_WORD + " " + CommandTestUtil.VALID_NUSNET_AMY);
Apologies for all these whitespace changes, some weird stuff happened when rebasing

2024-03-27 13:31 UTC, ForAeons commented on src/main/java/seedu/address/logic/LogicManager.java
> +        AutoCompleteCommand.initialize(
I think thats a great point. I have do another PR to address this.

2024-03-27 15:04 UTC, tituschewxj requested changes
Thanks for adding autocomplete for NUS_NET! I've tested it and it works great! I've also left some nits for this.

2024-03-27 15:04 UTC, tituschewxj commented on src/main/java/seedu/address/logic/autocomplete/AutoCompleteNusNetId.java
> +    private static final Pattern NUSNET_ID_FORMAT = Pattern.compile("nn/(.*)");
Is it possible to use the constant from `CliSyntax`?
```suggestion
    private static final Pattern NUSNET_ID_FORMAT = Pattern.compile(PREFIX_NUSNET.getPrefix() + "(.*)");
```

2024-03-27 15:04 UTC, tituschewxj commented on src/main/java/seedu/address/logic/parser/AddressBookParser.java
> +    private static final Pattern NUSNET_ID_FORMAT = Pattern.compile("nn/(.*)");
Ditto

2024-03-27 15:04 UTC, tituschewxj commented on src/main/java/seedu/address/logic/autocomplete/AutoCompleteNusNetId.java
> +     * @param nusNetIds the NUSNET IDs to initialize the trie with
```suggestion
     * Initializes the NUSNET ID trie with the given NUSNET IDs. This method should be called once at
     * the start of the initialization of LogicManager.
     *
     * @param nusNetIds the NUSNET IDs to initialize the trie with
```

2024-03-27 15:04 UTC, tituschewxj commented on src/main/java/seedu/address/logic/autocomplete/AutoCompleteNusNetId.java
> +     */
```suggestion
    /**
     * Update the NUSNET ID trie with the given NUSNET IDs. This method is just a wrapper for the
     * initialize method in Trie to make the intention clearer.
     *
     * @param nusNetIds the NUSNET IDs to update the trie with
     */
```

2024-03-27 23:59 UTC, ForAeons commented on src/main/java/seedu/address/logic/LogicManager.java
> +            || command instanceof EditPersonCommand) {
Thats a great point

2024-03-27 23:59 UTC, ForAeons commented on src/main/java/seedu/address/logic/autocomplete/AutoCompleteNusNetId.java
> +    private static final Pattern NUSNET_ID_FORMAT = Pattern.compile("nn/(.*)");
Will do

2024-03-28 03:04 UTC, tituschewxj approved these changes
LGTM!

2024-03-28 03:04 UTC, merged