Branch setcrs testing
AY2324S2-CS2103T-F13-1/tp pull request #82
Opened 2024-03-26 08:01 UTC by saiutkarsh33

- Created unit tests for set course command and its related classes

2024-03-27 15:23 UTC, tituschewxj requested changes
Thanks for adding the tests! I have nits for the naming in `CustomAssertionError`, as the naming is quite ambiguous currently.

2024-03-27 15:23 UTC, tituschewxj commented on src/test/java/seedu/address/logic/commands/CustomAssertionError.java
> +public class CustomAssertionError extends AssertionError {
**Unless** we have other custom assertions to add, consider changing the name `CustomAssertionError` to `InappropriateMethodCallAssertionError`, as it reduces ambiguities.

>[!IMPORTANT]
>You should change all instances of this name if you decide to change the name.

2024-03-27 15:23 UTC, tituschewxj commented on src/test/java/seedu/address/logic/commands/CustomAssertionError.java
> +    }
If you are sticking with `CustomAssertionError` for the class name, we should change this method name to `throwInappropriateMethodCallAssertion`.

Then we should need to have another constructor and use the constant for this.
```suggestion
    public static void throwInappropriateMethodCallAssertion() {
        throw new CustomAssertionError(INAPPROPRIATE_METHOD_CALL_MESSAGE);
    }
```

2024-03-27 15:23 UTC, tituschewxj commented on src/test/java/seedu/address/logic/commands/CustomAssertionError.java
> +    private static final String DEFAULT_MESSAGE = "This method should not be called.";
Perhaps a better name would be:
```suggestion
    private static final String INAPPROPRIATE_METHOD_CALL_MESSAGE = "This method should not be called.";
```

2024-04-01 14:03 UTC, tituschewxj approved these changes
LGTM! You don't have to do the changes in my note in this PR, since I don't want to hold back this PR from being merged. But if you do, then it's good too.

>[!NOTE]
>Instead of `InappropriateMethodCallAssertionError.throwDefault();`, you can just use `throw new InappropriateMethodCallAssertionError();`. And you can remove the `InappropriateMethodCallAssertionError#throwDefault` method, and the `InappropriateMethodCallAssertionError(String message)` constructor after doing this.

2024-04-02 08:33 UTC, ForAeons commented on src/test/java/seedu/address/logic/commands/InappropriateMethodCallAssertionError.java
> +
Can we move this file into commands/exceptions/

2024-04-02 08:37 UTC, ForAeons requested changes
Just some nits

2024-04-02 08:37 UTC, ForAeons commented on src/test/java/seedu/address/logic/commands/InappropriateMethodCallAssertionError.java
> +
Can we move this class into commands/exception package

2024-04-02 08:37 UTC, ForAeons commented on src/test/java/seedu/address/logic/parser/ParserUtilTest.java
>      private static final String VALID_NAME = "Rachel Walker";
```suggestion
    private static final String INVALID_COURSE = "CS";
    
    private static final String VALID_NAME = "Rachel Walker";
```

2024-04-02 08:37 UTC, ForAeons commented on src/test/java/seedu/address/logic/parser/ParserUtilTest.java
> +    private static final String VALID_COURSE = "CS2101";
```suggestion
    private static final String VALID_COURSE = "CS2101";
```

2024-04-02 08:37 UTC, ForAeons commented on src/test/java/seedu/address/storage/StorageManagerTest.java
```suggestion
```

2024-04-02 08:37 UTC, ForAeons commented on src/test/java/seedu/address/logic/commands/AddCommandTest.java
> -            throw new AssertionError("This method should not be called.");
I agree with titus on this. I think is good to explicitly use the throw keyword

2024-04-02 08:38 UTC, ForAeons commented on src/test/java/seedu/address/logic/commands/AddCommandTest.java
>          }
I agree with titus on this. I think is good to explicitly use the throw keyword

2024-04-03 11:51 UTC, tituschewxj approved these changes
LGTM!

2024-04-04 09:45 UTC, ForAeons approved these changes
Thanks a lot for making the changes! LGTM

2024-04-04 09:45 UTC, merged