Use up-down arrows to navigate previous commands
AY2324S2-CS2103T-F13-1/tp pull request #89
Opened 2024-03-26 17:06 UTC by belligerentbeagle

Resolves #88

2024-03-27 07:50 UTC, Anant1902 approved these changes
LGTM! Great job with this feature Ethan.

2024-03-27 10:18 UTC, saiutkarsh33 requested changes
Overall, Looks good. Just some minot nitpicks but overall, LGTM

2024-03-27 10:18 UTC, saiutkarsh33 commented on src/main/java/seedu/address/model/person/NusNet.java
Is there a reason why " is on another line here?

2024-03-27 10:18 UTC, saiutkarsh33 commented on src/test/java/seedu/address/ui/CommandHistoryTest.java
Very rigorous unit testing here. bravo!

2024-03-27 10:18 UTC, saiutkarsh33 commented on src/main/java/seedu/address/ui/CommandHistory.java
Javadocs could be more varied/ thorough

2024-03-27 13:25 UTC, ForAeons requested changes
Amazing quality of life feature, just a few nits

2024-03-27 13:25 UTC, ForAeons commented on src/main/java/seedu/address/ui/CommandBox.java
> +        commandTextField.setOnKeyPressed(this::handleArrowKeyPressed);
Could you refactor this into `handleKeyPressEvent` to apply SLAP?

```
    private void handleKeyPressEvent(KeyEvent e) {
        switch (e.getCode()) {
        case TAB:
            handleTabKeyPressEvent(e);
            break;
        case UP:
            // fall through
        case DOWN:
            handleArrowKeyPressed(e);
        default:
            break;
        }
    }
```

2024-03-27 15:48 UTC, tituschewxj commented on src/main/java/seedu/address/model/person/NusNet.java
>          + "followed by 7 digits";
This resolves #96

2024-03-27 17:48 UTC, belligerentbeagle commented on src/main/java/seedu/address/model/person/NusNet.java
I'm not sure either, I believe it was previously @ForAeons 's code
@ForAeons any reason? else I'll just put it to single line

2024-03-27 17:48 UTC, belligerentbeagle commented on src/main/java/seedu/address/model/person/NusNet.java
Oh and thanks for helping me review @saiutkarsh33

2024-03-27 17:49 UTC, belligerentbeagle commented on src/main/java/seedu/address/ui/CommandBox.java
> +        commandTextField.setOnKeyPressed(this::handleArrowKeyPressed);
Sure!

2024-03-27 17:59 UTC, belligerentbeagle commented on src/test/java/seedu/address/ui/CommandHistoryTest.java
Thanks man!

2024-03-27 18:00 UTC, belligerentbeagle commented on src/main/java/seedu/address/ui/CommandHistory.java
Done

2024-03-28 09:25 UTC, ForAeons requested changes
Just one final nit, we can merge this afterwards

2024-03-28 09:25 UTC, ForAeons commented on src/main/java/seedu/address/ui/CommandBox.java
> +        if (event.getCode().toString().equals("UP") || event.getCode().toString().equals("DOWN")) {
Just one final nit: since the HandleKeyPress function already checks for the key pressed, theres actually no need to check for key again here

2024-03-28 09:37 UTC, belligerentbeagle commented on src/main/java/seedu/address/ui/CommandBox.java
> +        if (event.getCode().toString().equals("UP") || event.getCode().toString().equals("DOWN")) {
okay!

2024-03-28 09:42 UTC, belligerentbeagle commented on src/main/java/seedu/address/ui/CommandBox.java
> +        if (event.getCode().toString().equals("UP") || event.getCode().toString().equals("DOWN")) {
Side qn, is this considered like code quality improvement or

2024-03-28 10:21 UTC, ForAeons commented on src/main/java/seedu/address/ui/CommandBox.java
> +        if (event.getCode().toString().equals("UP") || event.getCode().toString().equals("DOWN")) {
I would consider it code quality/style since logic wise this makes no difference

2024-03-28 11:16 UTC, ForAeons approved these changes
Fantastic work!

2024-03-28 11:19 UTC, merged