feat: add student
AY2324S2-CS2103T-F13-1/tp pull request #9
Opened 2024-02-24 13:32 UTC by ForAeons

2024-02-26 05:05 UTC, tituschewxj requested changes
Thanks for fast PR. I have some nits you may want to consider.

Side note: I think we should just keep `Person.java` instead of changing it to `Student.java`, as there would be a lot of merge conflicts if we changed it. But we should add a JavaDocs comment in `Person.java` to explain that Person is essentially just representing a student.

2024-02-26 05:05 UTC, Anant1902 approved these changes
Great job on your first PR. It is evident that you have taken time to thoroughly understand how the codebase works, successfully changing all aspects of the code that are affected by your feature implementation. Keep it up :)

2024-02-26 06:40 UTC, ForAeons commented on src/main/java/seedu/address/storage/JsonAdaptedPerson.java
> +    private final String nusnet;
My bad for the typo, will fix in the next commit 👍🏻

2024-02-26 06:45 UTC, ForAeons commented on src/main/java/seedu/address/logic/commands/EditCommand.java
Should we rename to EditPersonCommand since we are sticking to person

2024-02-26 13:51 UTC, tituschewxj reviewed
Thanks for the changes! Just a more few nits to consider.

Maybe you can consider updating the JavaDocs for the rest of the `PersonCommandParser` classes? I've included an example in my suggestions in the `FindPersonCommandParser.java` file.

2024-02-26 13:51 UTC, tituschewxj commented on src/main/java/seedu/address/logic/commands/AddPersonCommand.java
>      public static final String MESSAGE_USAGE = COMMAND_WORD + ": Adds a person to the address book. "
Also NUS NET as a parameter here?

2024-02-26 13:51 UTC, tituschewxj commented on src/main/java/seedu/address/storage/JsonAdaptedPerson.java
> +            @JsonProperty("email") String email, @JsonProperty("nus_net") String nusNet,
Perhaps we should use `nusNet` instead of `nus_net`? According to the [Google Json Style Guide](https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format), property names must be camel-cased.
```suggestion
            @JsonProperty("email") String email, @JsonProperty("nusNet") String nusNet,
```

2024-02-26 13:51 UTC, tituschewxj commented on src/main/java/seedu/address/logic/parser/FindPersonCommandParser.java
>   * Parses input arguments and creates a new FindCommand object
```suggestion
 * Parses input arguments and creates a new FindPersonCommand object
```

2024-02-26 13:51 UTC, tituschewxj commented on src/main/java/seedu/address/logic/parser/FindPersonCommandParser.java
>       * and returns a FindCommand object for execution.
```suggestion
     * Parses the given {@code String} of arguments in the context of the FindPersonCommand
     * and returns a FindPersonCommand object for execution.
```

2024-02-27 00:51 UTC, ForAeons commented on src/main/java/seedu/address/storage/JsonAdaptedPerson.java
> +            @JsonProperty("email") String email, @JsonProperty("nus_net") String nusNet,
My bad, I assumed that json is snaked_cased

2024-02-27 05:47 UTC, tituschewxj approved these changes
Thanks for the changes! LGTM!

2024-02-27 05:53 UTC, merged