Update DG
AY2324S2-CS2103T-F13-1/tp pull request #95
Opened 2024-03-27 10:31 UTC by saiutkarsh33

- Added a few lines to the DG with respect to set course

2024-03-27 13:19 UTC, ForAeons requested changes
LGTM, just some small nits

2024-03-27 13:19 UTC, ForAeons commented on docs/DeveloperGuide.md
> +Step 5. The user wants to set the course name. He enters the command setcrs CS2103T, causing the course name to appear on the main window's title.
```suggestion
Step 5. The user wants to set the course name. He enters the command `setcrs CS2103T`, causing the course name to appear on the main window's title.
```

2024-03-27 13:19 UTC, ForAeons commented on docs/DeveloperGuide.md
> +      in upper or lower case, and 1234 can be any 4 digit number. Y is optional
```suggestion
      Enter setcrs followed by a whitespace, followed by a course code in the format `XXYYYYZ`, where X and Z can be any letter
      in upper or lower case, Z is optional and YYYY can be any 4 digit number.
```

2024-03-27 14:13 UTC, tituschewxj approved these changes
Apart from the nits raised by @ForAeons, LGTM!

2024-03-28 04:53 UTC, ForAeons approved these changes

2024-03-28 04:53 UTC, merged